"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.zoll.model.product_unit import ProductUnit

from deutschland import zoll

globals()["ProductUnit"] = ProductUnit
from deutschland.zoll.model.product_units_data import ProductUnitsData


class TestProductUnitsData(unittest.TestCase):
    """ProductUnitsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductUnitsData(self):
        """Test ProductUnitsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProductUnitsData()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
