"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.zoll.model.products_data import ProductsData

from deutschland import zoll

globals()["ProductsData"] = ProductsData
from deutschland.zoll.model.products import Products


class TestProducts(unittest.TestCase):
    """Products unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProducts(self):
        """Test Products"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Products()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
