"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.zoll.model.categories_data import CategoriesData

from deutschland import zoll

globals()["CategoriesData"] = CategoriesData
from deutschland.zoll.model.categories import Categories


class TestCategories(unittest.TestCase):
    """Categories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategories(self):
        """Test Categories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Categories()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
