"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.zoll.model.product import Product

from deutschland import zoll

globals()["Product"] = Product
from deutschland.zoll.model.products_data import ProductsData


class TestProductsData(unittest.TestCase):
    """ProductsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductsData(self):
        """Test ProductsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProductsData()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
