"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.zoll.model.countries_data import CountriesData

from deutschland import zoll

globals()["CountriesData"] = CountriesData
from deutschland.zoll.model.countries import Countries


class TestCountries(unittest.TestCase):
    """Countries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountries(self):
        """Test Countries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Countries()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
