"""
    Einfuhrzoll API

    Abfragen von Importzöllen und Wechselkursen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.zoll.model.country import Country

from deutschland import zoll


class TestCountry(unittest.TestCase):
    """Country unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountry(self):
        """Test Country"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Country()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
